version: 2

seeds:
  - name: system_1_customers
    config:
      column_types:
        customer_id: int
        incremental_counter: int
        favourite_colour: varchar(100)
        row_timestamp: timestamp
