version: 2

seeds:
  - name: watermarks
    description: watermarks table
    config:
      column_types:
        target_table_type: varchar(250)
        target_table_name: varchar(250)
        source_table_name: varchar(250)
        watermark: varchar(250)
        run_time: timestamp
